export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_ERROR = "ADD_ADDRESS_ERROR";

export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";

export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const EDIT_ADDRESS_ERROR = "EDIT_ADDRESS_ERROR";