export const CART_ADD = "CART_ADD";
export const CART_ADD_ERROR = "CART_ADD_ERROR";

export const CART_GET = "CART_GET";
export const CART_GET_ERROR = "CART_GET_ERROR";

export const INCREMENT = "INCREMENT";
export const INCREMENT_ERROR = "INCREMENT_ERROR";

export const DECREMENT = "DECREMENT";
export const DECREMENT_ERROR = "DECREMENT_ERROR";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_ERROR = "DELETE_ITEM_ERROR";

export const DELETEALL_ITEM = "DELETEALL_ITEM";
export const DELETEALL_ITEM_ERROR = "DELETEALL_ITEM_ERROR";

export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_ERROR = "UPDATE_ITEM_ERROR";

export const MODAL_HANDLER = 'MODAL_HANDLER'
