export const ORDER_PRODUCT = "ORDER_PRODUCT";
export const ORDER_PRODUCT_ERROR = "ORDER_PRODUCT_ERROR";

export const GET_ORDER_PRODUCT = "GET_ORDER_PRODUCT";
export const GET_ORDER_PRODUCT_ERROR = "GET_ORDER_PRODUCT_ERROR";