export const UPLOAD_PRODUCT = "UPLOAD_PRODUCT";
export const UPLOAD_PRODUCT_ERROR = "UPLOAD_PRODUCT_ERROR";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const FILTER_PRODUCT_ERROR = "FILTER_PRODUCT_ERROR";

export const SEARCH_TERM = "SEARCH_TERM";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const HIGHT_LOW = "HIGHT_LOW";

export const GET_MY_PRODUCT = "GET_MY_PRODUCT";
export const  GET_MY_PRODUCT_ERROR = " GET_MY_PRODUCT_ERROR";

export const GET_INDIVIDUAL_PRODUCT = "GET_INDIVIDUAL_PRODUCT";
export const GET_INDIVIDUAL_ERROR = "GET_INDIVIDUAL_ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const MODAL_TOGGLE = "MODAL_TOGGLE";
export const MODAL_PRODUCT = "MODAL_PRODUCT";

