export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_ERROR = "ADD_REVIEW_ERROR";

export const GET_REVIEW = "GET_REVIEW";
export const GET_REVIEW_ERROR = "GET_REVIEW_ERROR";

export const GET_ALL_REVIEW = "GET_ALL_REVIEW";
export const GET_ALL_REVIEW_ERROR = "GET_ALL_REVIEW_ERROR";
