export const ADMIN_REGISTER_USER = "ADMIN_REGISTER_USER";
export const ADMIN_REGISTER_USER_ERROR = "ADMIN_REGISTER_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
export const LOGIN_WITH_GOOGLE_ERROR = "LOGIN_WITH_GOOGLE_ERROR";

export const LOGIN_WITH_FACEBOOK = "LOGIN_WITH_FACEBOOK";
export const LOGIN_WITH_FACEBOOK_ERROR = "LOGIN_WITH_FACEBOOK_ERROR";

export const ACTIVE_ACCOUNT = "ACTIVE_ACCOUNT";
export const ACTIVE_ACCOUNT_ERROR = "ACTIVE_ACCOUNT_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const ISAUTHENTICATE = "ISAUTHENTICATE";
export const FIND_MAIL = "FIND_MAIL";
export const FIND_MAIL_ERROR = "FIND_MAIL_ERROR";
export const RECOVER_PASS = "RECOVER_PASS";
export const RECOVER_PASS_ERROR = "RECOVER_PASS_ERROR";
export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";

export const AVATAR_UPDATE = "AVATAR_UPDATE";
export const AVATAR_UPDATE_ERROR = "AVATAR_UPDATE_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPDATE_MYACCOUT = "UPDATE_MYACCOUT";
export const UPDATE_MYACCOUT_ERROR = "UPDATE_MYACCOUT_ERROR";

export const FRESH_USER = "FRESH_USER";
