export const ADMIN_REGISTER_USER = "ADMIN_REGISTER_USER";
export const ADMIN_REGISTER_USER_ERROR = "ADMIN_REGISTER_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const ISAUTHENTICATE = "ISAUTHENTICATE";
export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";

export const AVATAR_UPDATE = "AVATAR_UPDATE";
export const AVATAR_UPDATE_ERROR = "AVATAR_UPDATE_ERROR";

export const UPDATE_MYACCOUT = "UPDATE_MYACCOUT";
export const UPDATE_MYACCOUT_ERROR = "UPDATE_MYACCOUT_ERROR";

export const FRESH_USER = "FRESH_USER";
