export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const UPDATE_VENDOR_ERROR = "UPDATE_VENDOR_ERROR";

export const GET_MY_VENDOR = "GET_MY_VENDOR";
export const GET_MY_VENDOR_ERROR = "GET_MY_VENDOR_ERROR";

export const GET_VENDOR = "GET_VENDOR";
export const GET_VENDOR_ERROR = "GET_VENDOR_ERROR";

export const GET_ALL_VENDOR = "GET_ALL_VENDOR";
export const GET_ALL_VENDOR_ERROR = "GET_ALL_VENDOR_ERROR";

export const FOLLOW_VENDOR = "FOLLOW_VENDOR";
export const FOLLOW_VENDOR_ERROR = "FOLLOW_VENDOR_ERROR";
