export const WISH_ADD = "WISH_ADD";
export const WISH_ADD_ERROR = "WISH_ADD_ERROR";

export const WISH_GET = "WISH_GET";
export const WISH_GET_ERROR = "CWISH_GET_ERROR";

export const DELETE_ITEM_WISHLIST = "DELETE_ITEM_WISHLIST";
export const DELETE_ITEM_WISHLIST_ERROR = "DELETE_ITEM_WISHLIST_ERROR";

export const DELETEALL_ITEM_WISHLIST = "DELETEALL_ITEM_WISHLIST";
export const DELETEALL_ITEM_WISHLIST_ERROR = "DELETEALL_ITEM_WISHLIST_ERROR";

